### ISSUE TITLE
IndexerInterface.handles(URI) -- remove it or keep it?

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#101]
Throughout the development of this major version, a method was added to the indexer plugin interface, `handles(URI)`, for checking whether a file can be handled by the indexer. An output of `false` would immediately discard it (false positives on the other hand, would not be too harmful). Currently, this is being used for a quick check by file name: if the extension makes it clear that the file is not DICOM (jpg, txt, ...), then an indexation will not be attempted on it. There are a few issues on the inclusion of this method in our interface:

- The effective check is only implemented on the plugin side, which means it is not enforced at all. Although an implementation is demanded, it is still up to `index(URI)` to call it. We do not need the interface to enforce a method to achieve this.

- If we stick to pure DICOM indexation for the whole Dicoogle environment, this method would only become useful to tell apart DICOM files from those that are not, and would no longer need a distinct implementation for each plugin. The indexation process will eventually handle that with exceptions anyway.

- Only a few of our indexer plugins have been updated with an implementation of `handles`, namely "lucene" and "cbir".

So the question is: burninate it (restoring what we had some months ago) or keep it?

**Comment by fmgvalente** [comment]
I think that if we don't come up with a solution that does what's intended, 
namely negotiation of indexation via mime-type, we should at least leave it 
there even if we cannot enforce it. Ideally, there should be a negotiation 
process between the plugin and the core where the plugin says which mime types 
it supports and the core enforces the correct handling. If we remove that 
functionality we must then implement proper checks in each plugin, which is 
not unreasonable as no component should implicitly trust the other, but we 
will have a performance penalty in that we must now dispatch the same file to 
every plugin. The alternative is of course to restrict the tool merely to 
dicom files, but I think we have no need of that and it places an unneeded 
constraint.

**Comment by Enet4** [comment]
> If we remove that functionality we must then implement proper checks in each plugin, which is
not unreasonable as no component should implicitly trust the other, but we
will have a performance penalty in that we must now dispatch the same file to
every plugin.

This will not be that much of a penalty, in my opinion. It's only a check that will be performed on the plugin rather than the core, and the runtime environment is the same. Furthermore, 

>  The alternative is of course to restrict the tool merely to
dicom files, but I think we have no need of that and it places an unneeded
constraint.

This has actually been under heavy discussion lately, and the final word established so far from @bastiao is that we should stick to DICOM for both storage and indexation. The arguments made against generic storage and indexation are various, but here are a few that I recall: any content other than DICOM will not work with DICOM services; plugins for statistic purposes would become more complex, as they would have to ignore some of the stored files; and in it could blur the line between Dicoogle being a PACS archive or an EHR system. I also have some points in favour, but I think they do not fit in this issue.

The key matter is that the way this method was considered and implemented so far is not as useful as it was thought, and breaks compatibility without a sufficiently fair reason.

**Comment by bastiao** [comment]
we should keep it because it allows to define what the plugin can handle. returns true for all is always an option. there are other files that can be indexed, and there is no problem with that, if they have the proper DICOM metadata. Finally, we never know the next requirements, and I'm not seeing any potential benefits of remove it.
