### ISSUE TITLE
Cannot download the exported CSV Results

### ISSUE THREAD

**Issue by tmgodinho** [bioinformatics-ua/dicoogle#135]
When you click the export button nothing happens; 
The servlet generates successfully the temporary file but the webapp does not allow you to download the file. It requires the user to search on the temporary files to retrieve the csv.

Suggestion: A Download box must appear when the file is ready to be downloaded.

--- Moreover ---
Feedback should be given to the user when he clicks in the export results button.

Suggestion: A looping something or a message saying processing

**Comment by Enet4** [comment]
A loader element would fit in, and it's not hard to implement. Have a look at an [example](https://github.com/bioinformatics-ua/dicoogle/blob/dev/dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF/js/components/management/indexerView.js#L42-L44).

**Comment by Enet4** [comment]
I cannot reproduce. Could you state what you tried to export, the browser that you were using and the responses from the server?

**Comment by bastiao** [comment]
This should be probably an issue with characters codification (or large files).

**Comment by Enet4** [comment]
Actually, it seems to be a browser-dependent issue. I reproduced the problem with FireFox 40.0.3.

**Comment by Enet4** [comment]
Is this issue still a problem?
