### ISSUE TITLE
Configurations and logger to confs/ and logs/ directory

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#141]
such as:

- config.xml
- dicoogle.log

why? 
if we are using it in a docker container we may want this data outside container.

**Comment by Enet4** [comment]
The log file path is already configurable with a logger configuration file: `-Dlog4j.configurationFile=my-log-config.xml`

We could recreate the effect with Dicoogle's global configuration file.

**Comment by bastiao** [comment]
yeap. That's exactly the point of the issue, to use environment variable.
