### ISSUE TITLE
Not easy to repeat the query.

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#143]
after search a "refine query" button or mechanism should be provided. 

Reported by BMD Software.

**Comment by Enet4** [comment]
We could transform the query input component into something like a drawer that slides to the top when the search is executed, then allow the user to click or drag the lower border to open the drawer again. This would have been ideal, but so far I haven't found a React component that does this right off the bat.

**Comment by bastiao** [comment]
A button to "refine" a query, and back to "search" with the query inserted do the job.

**Comment by tmgodinho** [comment]
Milton also reported this problem.
I'll change the priority now!!
