### ISSUE TITLE
Login request only on localhost

### ISSUE THREAD

**Issue by darthunix** [bioinformatics-ua/dicoogle#145]
when I start a dicoogle server 2.0.0 on a server (aktru.viveya.local) I can't login from a remote client via web browser. the problem is in login request - it is send on http://127.0.0.1:8080/login, but not in http://aktru.viveya.local:8080/login. is it a bug or I don't see some property in config.xml?

**Comment by bastiao** [comment]
I detected a problem with redirect in nginx and using vhosts. Not sure if the case, but it may be fixed in next release.

**Comment by Enet4** [comment]
That is indeed a bug in 2.0.0 and has already been fixed for the next patch. Meanwhile, the other issue where a proxy passing to an endpoint with a non-null path after the host (e.g. "http://www.mywebsite.org/dicoogle") breaks the webapp has been filed in #147.

**Comment by bastiao** [comment]
Fixed already.
