### ISSUE TITLE
Make webapp function properly behind a proxy pass

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#147]
If the webapp service is behind a proxy and redirecting from a URL with a non-null path after the host (e.g "www.dicoogle.com/demo"), the application will not work because the client will resolve relative paths without taking that base path section of the URL into account: `/search` would resolve to "www.dicoogle.com/#/search" instead of "www.dicoogle.com/demo/#/search".

What would you suggest to solve this properly?

**Comment by bastiao** [comment]
window.location.href, can solve the problem, right?

**Comment by Enet4** [comment]
I'm afraid that property alone will not resolve some ambiguities. Consider a case where the webapp is, for some reason, bound to "http://www.mypacs.org/search". Wouldn't the application assume that the base endpoint is "http://www.mypacs.org"?

**Comment by bastiao** [comment]
I think the problem is opposite. 

For instance, if you open www.dicoogle.com/demo/ the first page, that variable will be: http://www.dicoogle.com/demo/#/login 

Then if you move to search it will be:

http://www.dicoogle.com/demo/#/search.

The base is http://www.dicoogle.com/demo/ but to get it, we still need to replace the suffix. What do you think?

Or do you propose any other solution?

**Comment by Enet4** [comment]
> For instance, if you open www.dicoogle.com/demo/ the first page, that variable will be: http://www.dicoogle.com/demo/#/login

The href property will only resolve to that because of the React router, and we have full control of these redirections. In cases where the browser navigates directly to "www.dicoogle.com/demo/", the base endpoint can be retrieved in our [Loading view](https://github.com/bioinformatics-ua/dicoogle/blob/dev/dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF/js/components/login/loadingView.js#L27-L37). However, the browser will not always land on it directly.

**Comment by Enet4** [comment]
All right, let me think properly. So far we've only pondered over the case of embedding the webapp in the main server. In other cases, the Dicoogle server's endpoint has to be configured manually anyway.

- For the former cases, the webapp is always served in "/". Always. Our current routing uses hash-based routes that do not change the service endpoint. For instance, "http://www.dicoogle.com/demo/#/search" is actually served by "http://www.dicoogle.com/demo/", while retaining the hash part of the URL. The base Dicoogle endpoint will already be in `window.location.pathname`.
- For the cases where the webapp is not served in the base of all Dicoogle services, the best thing that we can do is to make this property configurable in deployment time, rather than fixing it in the bundling process.

**Comment by Enet4** [comment]
Closed with #131.
