### ISSUE TITLE
Shutdown plugins when terminating the server

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#149]
Although we have a Dicoogle plugin set interface exposing a [shutdown()](https://github.com/bioinformatics-ua/dicoogle/blob/dev/sdk/src/main/java/pt/ua/dicoogle/sdk/PluginSet.java#L115) event method and a [shutdown()](https://github.com/bioinformatics-ua/dicoogle/blob/dev/dicoogle/src/main/java/pt/ua/dicoogle/plugins/PluginController.java#L260) method in our plugin controller, none of these are actually being called. Maybe it was, back in the remote GUI version, but not anymore. We should probably hook this to a termination signal.

**Comment by bastiao** [comment]
@Enet4 seems that we going to address this at #115. So it may make sense to close this one?

**Comment by Enet4** [comment]
#115 does not fix this bug. It proposes a different way of implementing plugins, but that alone does not ensure that a `shutdown` always takes place. In addition, I am still hoping that this can be done without a major version of Dicoogle.

**Comment by Enet4** [comment]
Dicoogle has behaved like this for so long that it's best to push this to the next major version, so as to prevent surprses.
