### ISSUE TITLE
StorageInterface: "at" method should also contains optional arguments

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#165]
In the same way, of storage, we may want for instance to apply a decompressor. So the SDK should have this optional parameters to handle that requests that could be applied by that layer.

It was already discussed the same for store and index methods.

**Comment by Enet4** [comment]
But the `at` method is for reading, right? The decompression procedure to use would depend on how the file was compressed in the first place, and should be abstracted from the user. Is there any other use for optional arguments in this method?

**Comment by bastiao** [comment]
No, it is not. It depends on requested TransferSyntax.
