### ISSUE TITLE
Help: Fail to build dicoogle

### ISSUE THREAD

**Issue by Vial17** [bioinformatics-ua/dicoogle#184]
Hello, I am new to dicoogle and trying to build it. But after running "npm install", I end up with errors. Could anyone tell me how to fix this? 
npm-debug is here:

810 verbose afterAdd C:\Documents and Settings\GPIS\Application Data\npm-cache\react-font-awesome\1.0.3\package\package.json not in flight; writing
811 verbose afterAdd C:\Documents and Settings\GPIS\Application Data\npm-cache\react-font-awesome\1.0.3\package\package.json written
812 info dicoogle-webcore@0.10.1 Failed to exec prepublish script
813 error addLocalDirectory Could not pack C:\dicoogle-dev\webcore to C:\Documents and Settings\GPIS\Application Data\npm-cache\dicoogle-webcore\0.10.1\package.tgz
814 error addLocal Could not install C:\dicoogle-dev\webcore
815 verbose stack Error: dicoogle-webcore@0.10.1 prepublish: `npm run build`
815 verbose stack Exit status 1
815 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
815 verbose stack     at emitTwo (events.js:87:13)
815 verbose stack     at EventEmitter.emit (events.js:172:7)
815 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
815 verbose stack     at emitTwo (events.js:87:13)
815 verbose stack     at ChildProcess.emit (events.js:172:7)
815 verbose stack     at maybeClose (internal/child_process.js:818:16)
815 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
816 verbose pkgid dicoogle-webcore@0.10.1
817 verbose cwd C:\dicoogle-dev\dicoogle\src\main\java\pt\ua\dicoogle\server\web\webapp\WEB-INF
818 error Windows_NT 5.1.2600
819 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
820 error node v4.2.4
821 error npm  v2.14.12
822 error code ELIFECYCLE
823 error dicoogle-webcore@0.10.1 prepublish: `npm run build`
823 error Exit status 1
824 error Failed at the dicoogle-webcore@0.10.1 prepublish script 'npm run build'.
824 error This is most likely a problem with the dicoogle-webcore package,
824 error not with npm itself.
824 error Tell the author that this fails on your system:
824 error     npm run build
824 error You can get their info via:
824 error     npm owner ls dicoogle-webcore
824 error There is likely additional logging output above.

**Comment by bastiao** [comment]
we have released a new version of dicoogle, you can try and check if it works. Moreover, you have the binaries in website to use: www.dicoogle.com
BMD software also supports Dicoogle
