### ISSUE TITLE
Image thumbnail support

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#19]
We seem to have an implementation of thumbnail generation in the core of Dicoogle, but it is not integrated to indexation/searching procedures. We cannot have thumbnails in our web application unless:
- indexed images are issued and indexed for thumbnail generation
- these thumbnails are retrieved when listing a query result.

**Comment by Enet4** [comment]
I wish to address this matter by improving the server's image cache, so that it can keep both full images and thumbnails, as well as support other image formats. @bastiao what do you think?

**Comment by bastiao** [comment]
According to our F2F discussion, the WADO service will retrieve the thumbnails of the images.

**Comment by Enet4** [comment]
we do have an image web service at the core right now, all it needs is to support retrieving images by URI, rather than only by SOPInstanceUID. One could just implement the web service for retrieving only thumbnails into a plugin, but wouldn't this feature be as valuable as that one other service?

On the other hand, the WADO web service itself could use some work. Why isn't it compliant with the DICOM PS3.18?

**Comment by Enet4** [comment]
We can now retrieve thumbnails from the dic2png web servicek with #55. WADO-RS support will be addressed later (#45).
