### ISSUE TITLE
Web UI Plugin Interface

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#20]
With the deprecation of the Swing graphical plugin interface and the uprising of future use cases for Dicoogle, there comes a need for extendability at the web user interface level. Web Service plugins can provide web interfaces, but these are not integrated into the rest of the Dicoogle web application.

Here are some of the features that we are trying to cover:

- A user wants to perform a query by example (using content-based image retrieval). The best step into performing the query would be dragging and dropping an image into a file upload element in the Search page. The current querying interface is fixed to a basic querying method and an advanced querying method, which lack a means to send images. Future querying engines should be able to expose other query parameters in the interface itself.
- There may be cases where the querying engine(s) in use affect(s) what contents lie in a result. For instance, a CBIR query operation will provide results with a _similarity_ property, and may not provide the remaining information about the results (such as patient name, patient/study/series ID). On the other hand, there are other interesting ways to show results that might not be covered in the web site, such as showing a grid instead of a list.

Below is a diagram with my proposal. The Dicoogle web page will provide specific UI slots for plugins to be inserted into (multiple plugins in the same slot could be separated with tabs). A Web UI plugin would compose a JavaScript module and a package descriptor (using a "package.json" typically seen in Node.js). An example of a package descriptor can be seen below. At the `dicoogle` subtree, it must contain at least the file name of the module and a pointer to the slot meant to be attached to.

```json
{
  "name" : "cbir-query",
  "version" : "0.0.1",
  "description" : "CBIR Query-By-Example plugin",
  "dicoogle" : {
    "caption" : "Query by Example",
    "slot-id" : "query",
    "module-file" : "module.js"
  }
}
```

At the level of the actual module, a `DicoogleWeb` object would be exposed with some operations only relevant to the web interface. `issueQuery` would perform the query (thus passing all the data needed by the engine) and trigger a result plugin by invoking an event in the result slot. The `onResult` event function, implemented by each result web UI plugin, should take a list of results and expose them freely.

![webui](https://cloud.githubusercontent.com/assets/4738426/6602028/0edf7fbe-c811-11e4-8e44-f3db0fb87b80.png)

Let this issue be used to design and discuss Dicoogle's Web UI plugin interface. I will add more details as more suggestions and ideas come up.

**Comment by bastiao** [comment]
Good idea.

According to our discussion I'm suggestion to have kind of Javascript Plugin that should be loaded  at the bootstrap stage. 

In terms of functionality they should be able to hook at least:
* Query Builder 
* Search Results 
* Hook for the menu 
* Options 

Maybe is a good idea to have some kind of extensions like the following (or maybe, we can go for ECMAScript 6 or Typescript)

```
// Examples of possible inputs for confs: {“name”: “widgetname", “width”: 10, “height”: 20, .. ? }
// This kind of information could be provided in a separated JSON files, for instance: SampleSearchWidget.js and SampleSearchWidget.json 
var SampleSearchWidget = function SampleSearchWidget(confs){

SampleSearchWidget._base.apply(this, [confs.widgetname, “My Sample", confs.width, confs.height, etc...]);

}.inherit(SearchWidget).addToPrototype({

     __init : function(parent){
    }
    setProxy : function(globalProxy){
           // If need to access to some of global features/context? 
           // could be part of dicoogle-sdk.js ? only for the client-side part? 
    }

});

```

Just my 2 cents.

**Comment by Enet4** [comment]
Not bad, I say. The Dicoogle JS SDK is a critical to the solution, therefore. And the entire web UI plugin architecture would lie on the client side. Time to design dicoogle-sdk.js.

**Comment by Enet4** [comment]
The web core JavaScript module is done. Next I will implement some actually useful plugins and add slots to the Dicoogle web application.
https://github.com/bioinformatics-ua/dicoogle/tree/feature/webUI_plugin_interface/dicoogle/src/main/js

**Comment by Enet4** [comment]
Dicoogle Web Core has reached a functional version, and test query and result plugins are already implemented in [new/webUIplugin](https://github.com/bioinformatics-ua/dicoogle/tree/new/webUIplugin). I will start new issues to address future concerns.
