### ISSUE TITLE
Only enable access control if roles are configured

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#205]
Our latest version of Dicoogle breaks backwards compatibility because it requires a roles configuration file (roles.xml) for the WebUI service to work properly. Hence, after the problems that @tmgodinho is facing because of the new layer of access control, I suggest that we disable all access control if roles were not defined during deployment.

**Comment by bastiao** [comment]
Did you reproduce the bug?
I tried to remove roles.xml, remove the roles from users.xml and also remove all roles from my Web Plugins and it seems to work. Can you help me to reproduce it? Anyway, fixes are welcome!

**Comment by Enet4** [comment]
Assuming this already is the intended behaviour, we should see whether what @tmgodinho found is a bug in this part of the system.
