### ISSUE TITLE
Use Jetty with Restlet / JAX-RS / ...?

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#22]
Ever since we moved to Jetty to host our services, we went back from Restlet to servlet programming, which you know is significantly more frustrating and time consuming.

There is an [extension](https://github.com/tliron/restlet-jetty9) for adding Jetty 9 support to Restlet. I know we do have a bunch of servlets implemented already, but if we can manage to support both servlets and restlet resources under Jetty, what do you say about relying on Restlet again for future WS development?

**Comment by bastiao** [comment]
Nice.
That was our tried also but in the time that we did there was no extension to do that. Now there is.

**Comment by Enet4** [comment]
I just spoke to @tmgodinho and @fmgvalente on the subject. First of all, this extension might not work, or be a "not-so-well"-supported patch around the issue. Second, what we actually need is a practical abstraction to web service development. It may go through anything that can use Jetty as the server, so [JAX-RS](https://jax-rs-spec.java.net/) is also an option.

**Comment by bastiao** [comment]
Yes, sounds good plan for the future.

**Comment by Enet4** [comment]
Ok, so I just realized that Restlet SE actually does seem to support Jetty since around last November. http://maven.restlet.com/org/restlet/jse/org.restlet.ext.jetty/2.3.1/
So forget about needing a patch, apparently. We just need to add the right dependencies and keep existing servlets functional.

**Comment by Enet4** [comment]
I still couldn't find a way to make a Restlet Application work alongside servlets. I made a [question](http://stackoverflow.com/questions/29014767/have-restlet-working-alongside-http-servlets) on StackOverflow, in hope that it will give us a solution.

**Comment by Enet4** [comment]
I have managed to embed a Restlet application in a servlet, using the ServletAdapter (the JEE implementation of the servlet extension seems to be compatible with Java SE, apparently). I hope to publish this outcome soon.

When this merge is done, we will have a single server to configure, yet right now we support starting and stopping both **web server** (default port 8080) and **web services** (default port 6060). @bastiao, should we have a single start/stop server switch or a way to conditionally expose additional web services? The only reasonable decisions I'm thinking of right now is to either do the former and keep things simple; or support turning plugin web services on/off.

**Comment by bastiao** [comment]
Indeed. We will have one, and only one exposing web service. If you found a way to handle the restlet and expose it in Jetty or any other compatible way to put all the resources together, it will be very good and it avoids to port the features between web resources frameworks!

**Comment by Enet4** [comment]
Yes, I actually figured it out. I'll just make sure things are stable enough for a merge.

**Comment by Enet4** [comment]
This was taken care of in #41. For Dicoogle 3.0, I suggest modifying the SDK to support Restlet attachment rather than resources, as discussed in #42.
