### ISSUE TITLE
Web UI Export: Provide hints for field list.

### ISSUE THREAD

**Issue by tmgodinho** [bioinformatics-ua/dicoogle#221]
The users claimed that it was too bothersome to insert manually all the fields to be included in the exported results.

Milton suggested some sort of tick boxes, or a multi choice list to aid the user in this operation.

This was reported by Milton.

**Comment by Enet4** [comment]
We could use [react-select](https://github.com/JedWatson/react-select) to make a multi-select field with a searchable list of DICOM attributes. The [live demo](http://jedwatson.github.io/react-select/) even shows a similar example.

**Comment by bastiao** [comment]
@tmgodinho another suggestion that was discussed before was to have capability to save templates with predefined tags to export. I strongly believe that will make their interaction much easier.

**Comment by Enet4** [comment]
Indeed, I recall that one. I find it reasonable to contemplate both facilities. For the latter however, we need to sort out some kind of account-wise storage, right?

**Comment by bastiao** [comment]
yes, indeed.

**Comment by tmgodinho** [comment]
Relates with this issue: #182
