### ISSUE TITLE
Stick to one JSON library. 

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#23]
Dicoogle has currently two dependencies (`net.sf.json` and `com.google.gson`) that can do the same thing: encode and decode JSON. I may also point out that Gson is nicer to use than the other one. What do you think about sticking to just one dependency?

**Comment by fmgvalente** [comment]
On Friday 13 March 2015 03:17:14 Eduardo Pinho wrote:
> Dicoogle has currently two dependencies (`net.sf.json` and
> `com.google.gson`) that can do the same thing: encode and decode JSON. I
> may also point out that Gson is nicer to use than the other one. What do
> you think about sticking to just one dependency?

Its better to have a single one. However, I've not used either.
If code is not actively being developed using either I'd recommend jus to to  
choose one, port, and remove the other.

**Comment by Enet4** [comment]
Some of the sources are using `net.sf.json`, but they should be easily ported anyway. We may think of choosing the most practical and powerful for the task.

**Comment by Enet4** [comment]
Our conclusion was to stick to `net.sf.json`. I will look into removing the Gson dependency.
