### ISSUE TITLE
Jetty returning 403 forbidden

### ISSUE THREAD

**Issue by darthunix** [bioinformatics-ua/dicoogle#246]
I have built dicoogle from github sources on Ubuntu 16.04 LTS x86_64. After executing 
`java -jar dicoogle.jar ` 
browser opens http://localhost:8080 with response 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /. Reason:
<pre>    Forbidden</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```
`netstat -an | grep LISTEN | grep 8080` shows
`tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN `
Dicoogle's console log doesn`t show any errors at this moment. No proxy.

**Comment by bastiao** [comment]
Dear Denis, the problem is that the webapp is not compiled. So you need to do it and package the bundle again.

**Comment by darthunix** [comment]
It seems that all my problems were because of nmp version > 2 on Ubuntu 16.04. Now I am building with npm 1.3 and facing a problem with  `npm install`:
```
npm http 404 https://registry.npmjs.org/dicoogle-webcore
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/chucknorris/git/dicoogle/dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
```

web request [https://registry.npmjs.org/dicoogle-webcore](https://registry.npmjs.org/dicoogle-webcore) returns `{}` and it doesn't seem to be ok.

**Comment by darthunix** [comment]
It seem s the problem was in using npm version > 2

**Comment by brajovela** [comment]
i'm using Netbeans, how i can do to build de webapp? 


Best regards.

**Comment by bastiao** [comment]
It is not built with Netbeans.

Follow the instructions over there: 
https://github.com/bioinformatics-ua/dicoogle/tree/master/dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF

**Comment by brajovela** [comment]
what I have to install?  i'm using windows and linux but i have the same error.


best regards.

**Comment by Enet4** [comment]
You need Node.js (at least version 0.12) and npm (at least version 2.x.x) in order to build the web app.

1. In Windows, simply download the installation file from [the official website](https://nodejs.org/en/), which includes both. LTS is recommended for most users. In linux, software packages are available depending on the distribution (or package manager of choice).
2. Navigate to the Dicoogle web app ("dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF") using a command line.
3. `npm install`
4. Bundle the whole project, as normal, using Maven.

**Comment by brajovela** [comment]
Thanks for your help. 

i have another error: 
18 error Failed at the dicoogle-webapp@1.3.0 debug script 'gulp development'.
18 error This is most likely a problem with the dicoogle-webapp package,
18 error not with npm itself. 

Best regards.

**Comment by brajovela** [comment]
module.js:327
    throw err;
    ^

Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\USER FILES\Desktop\dicoogle-master\dicoogle\src\main\java\pt\ua\dicoogle\server\web\webapp\WEB-INF\gulpfile.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by Enet4** [comment]
Please run `npm install` with no other arguments, to be sure that all dependencies are installed before the building script is executed. If that still won't work, try running `npm update` beforehand, then try again.

**Comment by brajovela** [comment]
Thank you very much for your help. 

i have another error: 

pt/ua/dicoogle/server/web/rest/VersionResource.java:[36,32] error: cannot access JSONTokener

**Comment by Enet4** [comment]
I'm afraid that this matter has prolonged for longer than usual. Please contact [me](mailto:eduardopinho@ua.pt) or [Luís Bastião](mailto:bastiao@bmd-software.com) in private for further assistance. Note that the issue tracker is more fitting for the technical discussion of bugs, features and improvements to Dicoogle, rather than for tech support.
