### ISSUE TITLE
npm install - https://registry.npmjs.org/dicoogle-webcore returns {}

### ISSUE THREAD

**Issue by darthunix** [bioinformatics-ua/dicoogle#247]
I am building with npm 1.3 and facing a problem with  `npm install`:
```
npm http 404 https://registry.npmjs.org/dicoogle-webcore
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/chucknorris/git/dicoogle/dicoogle/src/main/java/pt/ua/dicoogle/server/web/webapp/WEB-INF
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
```

web request [https://registry.npmjs.org/dicoogle-webcore](https://registry.npmjs.org/dicoogle-webcore) returns `{}` and it doesn't seem to be ok.

**Comment by darthunix** [comment]
Solution `If the webapp shows an error due to the dicoogle-webcore package, simply navigate to the webcore package (at the base of the project: "./webcore"), and run npm install there. Then try building the webapp again.` didn't help me

**Comment by darthunix** [comment]
Ok, the problem was in old npm. Finally made a working build of dicoogle. This issue should be closed.

**Comment by Enet4** [comment]
You are correct, the webapp requires at least version 2 of npm, because older versions do not support local file system dependencies. We made a few adjustments for the next release that will free developers from building `dicoogle-webcore` before `dicoogle-webapp`, which will hopefully make the building process less confusing.

**Comment by brajovela** [comment]
I have this issue, i have npm version 2. 

If the webapp shows an error due to the dicoogle-webcore package, simply navigate to the webcore package (at the base of the project: "./webcore"), and run npm install there. Then try building the webapp again. 

didn't help me
