### ISSUE TITLE
Problem Finding Netbeans Maven Repository

### ISSUE THREAD

**Issue by renatosierra** [bioinformatics-ua/dicoogle#251]
Im trying to build the application but the netbeans repository is not answering anything on this URL http://bits.netbeans.org/maven2/ 

this makes the app unable to download the UI libraries etc...

**Comment by Enet4** [comment]
Hello! Thank you for reporting.

I actually cannot seem to reproduce the issue (bits.netbeans.org appears to be responsive right now). Maybe some firewall is preventing proper access to these services?

Nevertheless, I have created a new branch that clears the dependency to that repository. Please see whether building Dicoogle with this one helps: https://github.com/bioinformatics-ua/dicoogle/tree/imp/remove-more-rgui
