### ISSUE TITLE
dicoogle.jar file does not show the changes

### ISSUE THREAD

**Issue by brajovela** [bioinformatics-ua/dicoogle#254]
Login text translated to Spanish , I ran again in web-inf * npm install * and * npm build * and run the main project * mvn clean install * , but when I run the dicoogle.jar file does not show the changes , what could be wrong?

**Comment by Enet4** [comment]
It is not necessary to run the build script after calling `npm install`, it will be done automatically, according to the "pre-publish` script.

This doesn't seem like an issue with Dicoogle, but there are multiple reasons for unexpected behaviours:

1. Did your browser cache the previous file? You should force the browser to redownload everything, just to be sure (<kbd>Ctrl</kbd>+<kbd>F5</kbd>, or possibly <kbd>Shift</kbd>+<kbd>F5</kbd> in some systems).
2. Were the modified files part of the original source code? All JavaScript source code is in the "src/" folder. Bundles and other end files will be overridden by the various building scripts.
3. Sometimes (this is known by personal experience), Maven might fail to copy fresh resources to the jar file. This shouldn't happen when doing `mvn clean install`, but it doesn't hurt to try it a second time. In addition, make sure that you have executed the most recent jar file.

Furthermore, the web app can be tested separately without having it embedded in a jar file. The steps are simple:

1. Start Dicoogle locally or on a server: `java -jar dicoogle.jar -s`. The jar file does not need to contain the web application in this case.
2. Navigate to the web app's source code. Define the URL to Dicoogle's base endpoint using the `DICOOGLE_BASE_URL` environment variable, and bundle the source code: `DICOOGLE_BASE_URL=http://localhost:8080 npm run build` or `DICOOGLE_BASE_URL=http://localhost:8080 npm run debug`.
3. Start a static server on the web application's base folder. If you have python, the `run_server` script will do.
4. Open your browser and navigate to the static server: http://localhost:9000

But again, given that the people involved in Dicoogle from both PT.UA Bioinformatics and BMD software have managed to develop for Dicoogle without major problems, it is unlikely that this represents an actual issue with the project. Nevertheless, I will reopen this issue if you happen to prove us wrong. :)

**Comment by brajovela** [comment]
i run the jar and the web page login is blank. 

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create bundle.min.js line 31 > eval:15:415
ReferenceError: jQuery is not defined

1471498971055	addons.xpi	WARN	Exception running bootstrap method shutdown on webapps-team@lists.launchpad.net: ReferenceError: sss is not defined (resource://gre/modules/addons/XPIProvider.jsm -> file:///usr/share/mozilla/extensions/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/webapps-team@lists.launchpad.net/bootstrap.js:72:5)

**Comment by Enet4** [comment]
I'm sorry, but those error messages don't seem to relate to the original Dicoogle source code at all. You appear to have a faulty browser extension. We also cannot be held responsible for changes that you made to the code yourself. Please revert those changes and see if the application works. The application is also better supported by Chrome, although Firefox should work as well.

**Comment by brajovela** [comment]
i donwload the original Dicoogle source again, and when i run the jar file, i have this error and all the page is blank: 

console.warn: Asynchronous operation was aborted as selection changed.
console.error: 
  Message: Error: Connection closed, pending request to server1.conn0.50, type getOriginalLocation failed

Request stack:
Front<.request@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/protocol.js:1178:7
frontProto/</proto[name]@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/protocol.js:1338:14

**Comment by brajovela** [comment]
in windows, there is not error, only the page is blank.

**Comment by Enet4** [comment]
The error suggests that the web app is performing requests to an incorrect address. Have you defined the DICOOGLE_BASE_URL env variable properly before building it? What were your building steps? Please prefer replying in private for further assistance.
