### ISSUE TITLE
Deprecate StorageInterface#handles

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#257]
By definition, a certain storage is capable of handling a file with the given URI if and only if the scheme associated to the storage is equal to the file URI's scheme. Giving plugin developers the "opportunity" to change this behaviour via the [`handles`](https://github.com/bioinformatics-ua/dicoogle/blob/master/sdk/src/main/java/pt/ua/dicoogle/sdk/StorageInterface.java#L48) method is not only useless, but also an open door for bugs in plugins.

I propose that we replace this method declaration with the following code in the next major version, advising plugin developers not to use or override it.

``` java
@Deprecated
default public boolean handles(URI location) {
    Objects.requireNonNull(location);
    return Objects.equals(this.getScheme(), location.getScheme());
}
```

**Comment by jorgeMFS** [comment]
I agree. Due to this issue, I was having a StackOverFlowError due to my erroneous implementation.

`
public boolean handles(URI location) {
		return Objects.equals(getScheme(), this.AnonymousScheme);
	}
`
