### ISSUE TITLE
Deprecate "keyword" option in search services

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#275]
At the moment, the "keyword" option in a search or search-related service would supposedly ensure that the given query is interpreted as a keyword-based query or as a free text query. I believe that there currently are a few problems with it:

- In practice, our current implementation simply makes an awkwardly long query expansion when `keyword = false`, which is unnecessary and increases the complexity of a query, potentially leading to slower searches;
- A good indexer implementation would easily know how to deal with both kinds of queries automatically (see the Lucene 6 branch in our private repository for a reference);
- Our user interface already assumes that an automatic interpretation takes place (there is no "keyword-based" checkbox);
- There is no query, to my knowledge, that could be interpreted erroneously as a keyword-based query, and vice versa.

With this issue, and backed by the points above, I propose that the "keyword" attribute is marked as deprecated in the next major version of Dicoogle. Your feedback is appreciated.

**Comment by bastiao** [comment]
yes, agree. When we implemented the mechanism to automatically normalize the queries it was the first step to remove it. The SDK does not have references to this `keyword`. It's only a matter of taste, and clean few entries of code "keyword", and they are really a few: https://github.com/bioinformatics-ua/dicoogle/search?p=2&q=keyword&utf8=%E2%9C%93

**Comment by Enet4** [comment]
It's true, there aren't many occurrences of this keyword parameter, at least not enough to be a serious concern. The way I see it, we can wipe it out entirely in version 3.
