### ISSUE TITLE
Queries on Dicoogle

### ISSUE THREAD

**Issue by pvsaritha** [bioinformatics-ua/dicoogle#287]
Hi,

I would like to know whether Dicoogle provides SCP's for 1) Image storage 2) Storage commitment 3) MPPS 4) Modality worklist.  Also need to know if it supports DICOM TLS for advanced cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256.  

Please respond at the earliest since it is urgently needed.

thanks
Saritha

**Comment by Enet4** [comment]
Good day. You seem to be looking for a professional PACS archive solution. Please consider contacting [BMD Software](https://www.bmd-software.com/). The company provides consulting services, and may be able to fulfill your needs.

Our apologies for the delay, but our time zone would not allow us to reply sooner.

**Comment by bastiao** [comment]
We are already in contact, so we can close this issue.
