### ISSUE TITLE
Called AE Title Not Recognized

### ISSUE THREAD

**Issue by chsasank** [bioinformatics-ua/dicoogle#292]
Hi,

I'm new to dicoogle. I have installed Dicoogle and tried to echo to dicom server.

```
$ bash DicoogleServer.sh
```

In another window,
```
$ echoscu -v 127.0.0.1 1045
I: Requesting Association
F: Association Rejected:                    
F: Result: Rejected Permanent, Source: Service User                                     
F: Reason: Called AE Title Not Recognized   
```

I'm attaching log: [dicoogle.txt](https://github.com/bioinformatics-ua/dicoogle/files/909119/dicoogle.txt)

I have tried searching online and looking up dicoogle documentation but couldn't find how to resolve this. Can you please help me resolve this?

Thanks in advance,
Sasank.

**Comment by bastiao** [comment]
By default the default Application Entity Title is "DICOOGLE-STORAGE". Give a try.
Thanks.

**Comment by chsasank** [comment]
Thanks! That indeed works. Can you please point to me where I can change the default AET? I couldn't find it in config.xml

Also, connection seems to be getting timed out very often. Where can I change the timeout?

Thanks!
