### ISSUE TITLE
Uniformize Logging

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#31]
The project is currently relying on multiple logging frameworks, each class appearing to have an independent choice: either java.util.logging or Apache log4j. In addition, slf4j was actually included as a dependency, but barely used in our code.

My suggestion is to adopt slf4j to the entire project and future code, thus being completely abstracted from the underlying logging framework. There is a [tool](http://www.slf4j.org/migrator.html) for migrating our current code. I am currently experimenting with it in a separate branch. Meanwhile, I would like to hear your opinions.

**Comment by fmgvalente** [comment]
On Saturday 04 April 2015 12:24:14 Eduardo Pinho wrote:
> java.util.logging

I think java.util.logging is what I've been using. No deps and does everything 
that's required.

**Comment by Enet4** [comment]
Yes, but as mentioned, some relevant parts of Dicoogle are using log4j. The advantage of slf4j is that we can choose which one to use in deployment time.

**Comment by fmgvalente** [comment]
On Saturday 04 April 2015 13:09:16 Eduardo Pinho wrote:
> Yes, but as mentioned, some relevant parts of Dicoogle are using log4j. The
> advantage of slf4j is that we can choose which one to use in deployment
> time.

I don't see the fact of choosing an implementation for slf4j as representing 
any advantage whatsoever given our use cases for logging in dicoogle. It's 
hardly a requirement. My vote in this case goes for, all things being equal, 
simpler is better.

**Comment by Enet4** [comment]
We do not know whether java.util.logging will be enough in future generations, and slf4j introduces a portable abstraction without introducing much complexity code-wise:

    Logger logger = LoggerFactory.getLogger(nameOrClass);
    logger.info("reticulating splines");

This is not much different from what you're used to. Furthermore, since there's a tool for migrating to slf4j, we can easily adapt the entire project to the same API.

**Comment by fmgvalente** [comment]
On Saturday 04 April 2015 16:53:51 Eduardo Pinho wrote:
> We do not know whether java.util.logging will be enough in future
> generations, and slf4j introduces a portable abstraction without
> introducing much complexity code-wise:

We will *never* know if something will be enough other than using and 
verifying just that. For the use cases we currently have, I think it *is* 
enough (can't really say it will always be the case).
Does the interface facade provided by slf4j does anything that util.logging 
does not do? Because if not there is no reason to believe it will do so in the 
future.
I'm not particularly arguing about java.logging vs slf4j but for simplicity vs 
adding a dependency for no reason. I think that the code between both 
implementations is quite similar, and again, all things being equal, I prefer 
the standard implementation.

> 
>     Logger logger = LoggerFactory.getLogger(nameOrClass);
>     logger.info("reticulating splines");
Thanks, now I want to play SimCity again...

**Comment by Enet4** [comment]
Well, I won't strictly defend this approach. We can also manually convert existing log4j code to JUL and use it directly. Hopefully, @bastiao will be able to make a final decision on the subject. Then we'd better not forget to add the established logging convention to our wiki.

> Thanks, now I want to play SimCity again...

![you_cant_cut_back_on_logging](https://cloud.githubusercontent.com/assets/4738426/6995264/89586d4c-db34-11e4-9876-021eb15d9db4.png)

**Comment by fmgvalente** [comment]
On Saturday 04 April 2015 17:40:26 Eduardo Pinho wrote:
> Well, I won't strictly defend this approach. We can also manually convert
> existing log4j code to JUL and use it directly. Hopefully, @bastiao will be
> able to make a final decision on the subject. Then we'd better not forget
> to add the established logging convention to our wiki.
> > Thanks, now I want to play SimCity again...
> 
> ![you_cant_cut_back_on_logging](https://cloud.githubusercontent.com/assets/4
> 738426/6995264/89586d4c-db34-11e4-9876-021eb15d9db4.png)

Sir, you have won an Internet!

**Comment by Enet4** [comment]
I also discovered a few more annoyances of using JUL instead of slf4j:

- Retrieving a logger with the java.util.logging.Logger must be done by logger name, and we often want to associate it with a class. In slf4j we could be writing `LoggerFactory.getLogger(MyClass.class)` instead of `Logger.getLogger(MyClass.class.getName())`.
- slf4j supports 2-argument, as well as 1-argument and var-argument parameters to formatted logging, for all level methods. In JUL, formatted logging is only available in the `log` method, and does not include a 2-argument prototype. This can make some instructions simpler and faster in runtime. This one is a real example:
    
    logger.log(Level.INFO, "Fired Indexer: {0} for URI: {1}", new Object[]{pluginName, path}); // JUL
    logger.info("Fired Indexer: {} for URI: {}", pluginName, path); // slf4j

**Comment by Enet4** [comment]
As stated on the list of [recommended libraries](https://github.com/bioinformatics-ua/dicoogle/wiki/Libraries), slf4j is the standard logging interface. As such, do use slf4j for all logging purposes.
