### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by BeatusV** [bioinformatics-ua/dicoogle#336]
When trying to build the master using mvn install in root directory, i get the following error:

> /dicoogle/dicoogle/src/main/java/pt/ua/dicoogle/rGUI/client/windows/MainWindow.java:[460,66] error: incompatible types: Enumeration<TreeNode> cannot be converted to Enumeration<DefaultMutableTreeNode>

I run java on 9.0.4 , javac same
node on 9.5.0

Any ideas?

**Comment by Enet4** [comment]
Thank you for reporting. The current development branch won't compile on Java 9, but I believe that has been fixed in #309. Feel free to give it a try.

**Comment by BeatusV** [comment]
Sweet, build passes
