### ISSUE TITLE
Use S3 with Dicoogle

### ISSUE THREAD

**Issue by Rokshan2016** [bioinformatics-ua/dicoogle#377]
Hi @bastiao 

I am trying to use s3 for Dicoggle storage . Basically I want to read DICOM files from s3 and indexed it using Dicoogle . How to achieve this?

Any suggestion with be really helpful.

Thanks !

**Comment by Enet4** [comment]
Hello, @Rokshan2016. Thank you for your interest in Dicoogle.

This appears to be a typical use case for a *Storage* plugin. You can learn more about making storage plugins from the [learning pack](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/storage/). General plugin development guidelines are also available [here](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/developing-plugins/).

As this is not an actual bug report, or about developing for the core components of Dicoogle, I will be closing this issue. However, if you have any further questions about using and developing plugins for Dicoogle, feel free to use our separate [issue tracker](https://github.com/bioinformatics-ua/dicoogle-learning-pack/issues/new) at the learning pack repository.

**Comment by bastiao** [comment]
@Rokshan2016 quick tip: use NFS/SAMBA with AWS Storage Gateway. Depending on where lives the main server, iSCSI may be possible.
Best Regards.
