### ISSUE TITLE
Error in dicoogle build: Could not download Node.js from x64/node.exe

### ISSUE THREAD

**Issue by surajitiitkgp** [bioinformatics-ua/dicoogle#381]
I have loaded the dicoogle open source project in my netbeans sdk. Getiing some error when try to dedug the code. Below are the error message

`Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm) on project dicoogle: Could not download Node.js from: http://nodejs.org/dist/v6.9.1/x64/node.exe: Got error code 404 from the server. -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

After correcting the problems, you can resume the build with the command
  mvn <goals> -rf :dicoogle`

**Comment by Enet4** [comment]
Thank you for reporting. Which operating system are you attempting to build Dicoogle with?

It seems that the frontend Maven plugin is attempting to download Node.js from the wrong URL. On Windows, for example, it should be <http://nodejs.org/dist/v6.9.1/win-x64/node.exe>. In the mean time, this part of the building process can be safely replaced with the following steps:

1. Download and install Node.js + npm separately into your system. (minimum version is Node 6, but the latest LTS is recommended).
2. At the project's source code, navigate to "dicoogle/src/main/resources/webapp/" and run `npm install` there.
3. Then return to the root project and run `mvn install -Dskip.installnodenpm -Dskip.npm`.

**Comment by surajitiitkgp** [comment]
I am using Windows server 2012

**Comment by surajitiitkgp** [comment]
Even after downloading the error remains same.

**Comment by Enet4** [comment]
@surajitiitkgp The project's pom.xml has been adjusted in #382, can you please try again on [this branch](https://github.com/bioinformatics-ua/dicoogle/tree/imp/node10)?

**Comment by surajitiitkgp** [comment]
@Enet4 I have updated the pom.xml file. When I try to build this application it takes following path to download Nodejs "http://nodejs.org/dist/v10.15.3/x64/node.exe", But actual path is  "http://nodejs.org/dist/v10.15.3/win-x64/node.exe".  Now please let me know how can I configure this as default download URL.

**Comment by surajitiitkgp** [comment]
Finally, It executes after maven version upgrade. Previously, I was using v3.0.5 and the newer version is v3.6.0.
