### ISSUE TITLE
Cannot get the jars needed when the maven repository is in maintenance

### ISSUE THREAD

**Issue by wynn5a** [bioinformatics-ua/dicoogle#384]
Because the maven repository is in maintenance, http://bioinformatics.ua.pt/maven/content/repositories/mi/,
We can't get the jars for building the project, is there any way to share the jars? Or when the maintenance will be over?

**Comment by Enet4** [comment]
Our apologies for the inconvenience. Our Maven repository is back online, and we'll be looking into ways to make the project more resilient to down times.

**Comment by wynn5a** [comment]
Thanks, Closing
