### ISSUE TITLE
Requesting Dicoogle plugin & code

### ISSUE THREAD

**Issue by hihipch** [bioinformatics-ua/dicoogle#385]
Hello sir. I’m doctor Chul Hyoung Park from Department of Biomedical Informatics of Ajou University School of Medicine of South Korea. I’ve experienced a wonderful moment while I marked up and annotated images with pathologic demo of Dicoogle. We would definitely like to apply this program on our pathologic images from Ajou University Hospital. We have identified that it is using React API of Modern Web on developing plugin of dicoogle, however the plugin does not seem to fully support it yet. Therefore we are having difficulties in developing a new plugin, and it will be really helpful for us to take a closer look at the pathology plugin and its code that you’ve developed. Can we get the pathology plugin and its code that you've developed? Thank you so much for your considerations.

Chul Hyoung Park, MD

Department of Biomedical Informatics,

Ajou University School of Medicine

164 World cup-ro Yeongtong-gu, Suwon-si Gyeonggi-do, 16499, Republic of Korea

Telephone: 82-31-219-4471, FAX: 82-31-219-4472

Mobile: 82-10-6531-1435

e-mail: hihipch@gmail.com

**Comment by bastiao** [comment]
Addressed already by email.
