### ISSUE TITLE
SOP Class 1.2.840.10008.5.1.4.1.2.2.3

### ISSUE THREAD

**Issue by Neuroforge** [bioinformatics-ua/dicoogle#393]
Hello,

I am working with fo-dicom and dicoogle. The file i am working from is (https://github.com/fo-dicom/fo-dicom-samples/blob/master/Desktop/QueryRetrieve%20SCU/Program.cs)

It is specifically the C-GET request. The C-Find appears to work great!

[ERROR] No accepted presentation context found for abstract syntax: Study Root Query/Retrieve Information Model - GET [1.2.840.10008.5.1.4.1.2.2.3]

I was unable to see any options to alter/add this SOP class in Dicoogle.

Does dicoogle support this SOP class, or can it be configured to?

Is there any advice on how to make this library work with this dicom server?

**Comment by Enet4** [comment]
Apologies for the late reply. Regretfully, Dicoogle does not support C-GET commands at this time. One would have to resort to C-MOVE instead. In this context, the DICOM server then keeps a list of supported storage SOP classes.

**Comment by Neuroforge** [comment]
No worries. Thank you for the response.

It appears that the C-GET commands are generally poorly supported. Not sure why this is the case, but the C-Mode does appear to be more secure given the SCP holding 'credentials' for the client.

Thank you.

**Comment by Enet4** [comment]
That is true. I often hear that stakeholders are very often not interested in supporting C-GET, even suggesting that the command is retired (although AFAIK it is not). I wouldn't be opposed to someone contributing to Dicoogle with an implementation, but it would still be a low priority feature.

Thank you for your interest in Dicoogle, nonetheless.
