### ISSUE TITLE
maven install 

### ISSUE THREAD

**Issue by CriminalKidd** [bioinformatics-ua/dicoogle#399]
maven install error : [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:npm (npm install) on project dicoogle: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "E:\dicoogle-dev\dicoogle\target\node\node.exe" (in directory "E:\dicoogle-dev\dicoogle\src\main\resources\webapp"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]

**Comment by CriminalKidd** [comment]
1

**Comment by bastiao** [comment]
You provide only few details, however, it may be probably related with node-sass that does not find bindings for Windows. I pushed a patch for a branch, you can use on your own risk: 
https://github.com/BMDSoftware/dicoogle/commit/bbc6f9331d2019e5112fa85a24552f4ba98ee641

You can skip the node install part and use your own node/npm. 

```
mvn install -Dskip.installnodenpm
```

Strongly recommend to read: https://github.com/bioinformatics-ua/dicoogle/blob/dev/README.md

**Comment by CriminalKidd** [comment]
--- maven-clean-plugin:2.5:clean (default-clean) @ dicoogle ---
[INFO] Deleting E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ dicoogle ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\target\version.txt
[INFO] 
[INFO] --- frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) @ dicoogle ---
[INFO] Installing node version v10.15.3
[INFO] Copying node binary from E:\Repository\com\github\eirslett\node\10.15.3\node-10.15.3-win-x64.exe to E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\target\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 6.4.1
[INFO] Unpacking E:\Repository\com\github\eirslett\npm\6.4.1\npm-6.4.1.tar.gz into E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\target\node\node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.8.0:npm (npm install) @ dicoogle ---
[INFO] Running 'npm install' in E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\src\main\resources\webapp
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dicoogle-all 3.0.0-SNAPSHOT ........................ SUCCESS [  0.616 s]
[INFO] dicoogle-sdk ....................................... SUCCESS [  2.801 s]
[INFO] dicoogle-sdk-ext ................................... SUCCESS [  1.843 s]
[INFO] dicoogle 3.0.0-SNAPSHOT ............................ FAILURE [ 15.846 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.201 s
[INFO] Finished at: 2019-11-11T11:25:32+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:npm (npm install) on project dicoogle: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\target\node\node.exe" (in directory "E:\dicoogle-bug-fix_node_sass_dependency_win64\dicoogle\src\main\resources\webapp"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dicoogle

**Comment by CriminalKidd** [comment]
HTTP ERROR 403
Problem accessing /. Reason:
    Forbidden

**Comment by Enet4** [comment]
This usually happens when the webapp was not built into Dicoogle. Considering the issues encountered in #399, consider following the instructions on our [installation guide](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/building/#building-and-debugging-the-web-application) in order to _build the webapp directly_, and then running Maven:

0. Have Node.js (v10 recommended, v12 may not work yet) and npm installed in your system.
1. Navigate to "dicoogle/src/main/resources/webapp"
2. `npm install`
3. Navigate back to the source code root
4. `mvn install -Dnpm.skip -Dskip.installnodenpm`

**Comment by CriminalKidd** [comment]
thanks , node version issue
