### ISSUE TITLE
Integrate Sentry in Dicoogle Core

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#40]

**Comment by Enet4** [comment]
I suppose you mean this [Sentry](https://getsentry.com/welcome/)?

**Comment by bastiao** [comment]
yes. There are wrappers for Java already and Dicoogle has an general exception handler.

**Comment by Enet4** [comment]
Sounds like we can just stick to slf4j and take this [log4j2 appender]( https://github.com/getsentry/raven-java/blob/master/raven-log4j2/README.md). It should be easy once #36 is merged.

**Comment by Enet4** [comment]
Sentry support was added with #47.
