### ISSUE TITLE
accepted Socket issue

### ISSUE THREAD

**Issue by CriminalKidd** [bioinformatics-ua/dicoogle#402]
INFO  net.Association (Association.java:147) - Association(5) accepted Socket[addr=/127.0.0.1,port=51356,localport=100]
INFO  net.Association (Association.java:964) - Association(5): A-ASSOCIATE-RQ dicoogle-storage >> ANY-SCP
INFO  net.PDUEncoder (PDUEncoder.java:106) - dicoogle-storage(5) << A-ASSOCIATE-RJ[result=1, source=1, reason=7]: permanent called-AE-title-not-recognized
INFO  net.Association (Association.java:916) - dicoogle-storage(5): close Socket[addr=/127.0.0.1,port=51356,localport=100]

**Comment by rlebre** [comment]
https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/configuring/#configuration-file

**Comment by Enet4** [comment]
Can you please ensure that your DICOM client is correctly configured to refer to Dicoogle by its AE title? The default value is `DICOOGLE-STORAGE`.

**Comment by CriminalKidd** [comment]
I'm sure, because I've tried to modify aetitle

**Comment by bastiao** [comment]
It may be capitals letters usage. If there are more details, please re-open the issue.
