### ISSUE TITLE
Cannot find "dicoogle" in users.xml

### ISSUE THREAD

**Issue by maheshwarkuchana** [bioinformatics-ua/dicoogle#409]
I have installed and followed instructions mentioned in the website accordingly, but when I tried to log in with "dicoogle" username and "dicoogle" password it is throwing an error and unable to log in.

**Comment by Enet4** [comment]
What are the contents of "users.xml"? In the event that it is corrupted or empty, you can remove it and restart Dicoogle to construct it again.

**Comment by maheshwarkuchana** [comment]
Yeah its done it is working fine. Just one more doubt will dicoogle don't run in environments above Java 8?

**Comment by maheshwarkuchana** [comment]
I have one big issue which @Enet4 probably you can help me. 

I would like to explain the whole scenario of the problem I am facing.

1. We have a PC in Switzerland where the NATIVE format of patient scans and a review software (which can read native format files and display images) are present. Those NATIVE Format files can only be read by its manufacturer's software (example: Zeiss, Philips, Siemens etc). 
2. The review software has a functionality to convert NATIVE files to DICOM Format only if we provide a qualified DICOM Archive such as VISUPACS, FORUM etc.
3. In order for it to send the DICOM formatted files from PC in Switzerland to our place, we have to use DICOM gateway configuration tool.
4. The functionality of DICOM gateway is to transfer the files from local to remote location
5. For this purpose we have to provide IP address, AE title, Port number of both local and remote PCs
6. I have made port forwarding in remote system.
7. As the NATIVE data is present on the same system where DICOM gateway tool is installed, we use 127.0.0.1 and port number 11112.
8. So now the DICOM gateway takes the NATIVE data and ideally should send the data to my remote PC in dicom format.
9. At first we have to configure the DICOM gateway. For this to be successful, DICOM gateway checks whether the remote PC has a PACS software.
10. For this purpose, I have installed Orthanc as it is PACS.
11. Orthanc configuration.json file has information such as port number and AE title, which I have provided to the DICOM gateway tool.
12. When we run the sample connection tests, it ideally should show 5 green lights. Rather in our case they are just three. And rest two are RED in colour.
13. I checked the RED lights are for MWL Provider and Storage Commitment Provider which are not provided by the Orthanc
14. I have noticed that Orthanc provides MWL service as a plugin and I tried to make use of tutorial to make it for my purpose. But unfortunately, I am unable to do it.

I'm attaching the DICOM gateway picture here.
Hoping you got the clear picture of the problem, I am requesting you to help me out.

**Comment by maheshwarkuchana** [comment]
x-special/nautilus-clipboard
copy
file:///home/adventum/Downloads/InkedScreenshot%20from%202020-02-19%2014-03-55_LI.jpg

**Comment by Enet4** [comment]
I'm sorry, but we, as the developers of Dicoogle, are not in position to provide guidance for such a use case, much less in an issue tracker. The freely available resources on how to use and configure Dicoogle are available [here](https://bioinformatics-ua.github.io/dicoogle-learning-pack/). In a more advanced use case, we recommend contacting [BMD Software](https://www.bmd-software.com) for professional assistance.

Regarding the Java environment, this has occasionally been brought up in other issues. I just raised a new issue to keep track of this (#410). In short, we still recommend using Java 8 at the moment, although being able to use more recent versions would be nice to have in the future.
