### ISSUE TITLE
QIDO-RS: implement it following the API. 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#44]
Example of response (from NEMA/DICOM).

https://gist.github.com/bastiao/dcf0744dd96e9708fcf6

**Comment by Enet4** [comment]
Is this also for 3.0?

**Comment by bastiao** [comment]
It will be developed as Plugin. Unless a requirement as been raised to be supported in core (same for WADO-RS, STOW-RS).
