### ISSUE TITLE
Should we take down dicoogle-sdk-ext?

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#443]
This was meant to be used as a utility extension to the SDK, but in practice this hasn't been used in many years, and there is hardly any documentation around it. We do not advise its usage in the learning pack

So I believe we should refrain from publishing any 3.x.x versions of `dicoogle-sdk-ext` and remove the /ext directory at the upstream development branches for v3

Any pieces of this package which may be useful for someone can be brought back as independent packages with better documentation and focus.

**Comment by bastiao** [comment]
@Enet4 yes, we will take it down.

**Comment by Enet4** [comment]
Resolved by #493.
