### ISSUE TITLE
How to setup DICOMweb？

### ISSUE THREAD

**Issue by ziqiangxu** [bioinformatics-ua/dicoogle#454]
Need I install a plugin?

**Comment by Enet4** [comment]
Hello @ziqiangxu. You can see the full web API of Dicoogle in the [API hub](https://bioinformatics-ua.github.io/dicoogle-api/), with which you can index and perform searches. See also the [learning pack](https://bioinformatics-ua.github.io/dicoogle-learning-pack/) on how to prepare Dicoogle in general.

Standard DICOM Web services (QIDO, WADO, STOW) are not available in the core project, although they are available as commercial plugins. Please reach out to [BMD Software](https://www.bmd-software.com/) if this would be of your interest.

**Comment by ziqiangxu** [comment]
> You mentioned Standard DICOM Web services (QIDO, WADO, STOW) are available as commercial plugins. Can I know the pricing and procedures for setting up the DICOM Web services ?

You may contact them by submit your e-mail on the bottom of this [website](https://www.bmd-software.com/)  😃
