### ISSUE TITLE
the web plugin does not appear

### ISSUE THREAD

**Issue by Kesling515** [bioinformatics-ua/dicoogle#465]
I follow the step in this page "https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/webplugins/" to creat web ui plugin, and  already copy "module.js" and "package.json" above into my "WebPlugins" directory, but the web plugin does not appear.  I try to refresh my page and restart, it is not use. The server log has no information about load it.  
![image](https://user-images.githubusercontent.com/43846775/119800044-3a645280-bf0f-11eb-8826-98e6feec16d9.png)
![image](https://user-images.githubusercontent.com/43846775/119800151-549e3080-bf0f-11eb-852f-a3e01a0c669c.png)

The directory tree should look like this:
 DicoogleDir
 ├── Plugins
 |   └── ...
 ├── WebPlugins
 |   └── aetitle
 |       ├── package.json
 |       └── module.js
 ├── ...
 └── dicoogle.jar

**Comment by Enet4** [comment]
Thank you for reporting. We may need some more information to diagnose the issue.

- Could you share the web plugin's package.json?
- Does the browser report any errors in the console?
- Consider also logging out from Dicoogle (top-right corner) and logging in again, preferably with the default `dicoogle` user or another administrator user if no web plugin appears

**Comment by Kesling515** [comment]
@Enet4
 Hello, thanks for your reply.
1. My plugin's package.json as follows:
 {
  "name": "aetitle",
  "version": "0.1.0",
  "description": "a web ui plugin",
  "main": "module.js",
  "files": [
    "module.js"
  ],
  "scripts": {
    "build": "webpack --config webpack.prod.js",
    "build-debug": "webpack --config webpack.dev.js",
    "build-watch": "webpack --config webpack.dev.js --watch",
    "prepare": "npm run build"
  },
  "author": "Kesling515 <XXXXX@XXX.com>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "Kesling515/aetitle"
  },
  "keywords": [
    "dicoogle",
    "dicoogle-plugin"
  ],
  "dicoogle": {
    "slot-id": "settings",
    "caption": "Aetitle",
    "module-file": "module.js"
  },
  "devDependencies": {
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.2",
    "babel-loader": "^8.2.2",
    "babel-minify-webpack-plugin": "^0.3.1",
    "file-loader": "^3.0.1",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-merge": "^4.2.2"
  }
}
2. The browser does not report any errors in the console.
3. I have tried to log out from Dicoogle (top-right corner) and log in by default dicoogle user again, but it is useless.
And I run the program in Windows.

**Comment by Enet4** [comment]
Not long ago I double checked the web plugin functionality and its various supported slots, and only noticed a bug in Dicoogle 3 which could lead to plugins of different types being installed in a slot #478.

- Consider trying again with the patch in #478.
- There is access control in web plugins, which could be the reason why the web app is not showing any plugins. To be sure that this is not the problem, you can add `-Dwebui.permissive=1` when running Dicoogle.

**Comment by Enet4** [comment]
We believe that this issue will no longer be a problem with #497. If there are still issues in the upstream branch, please let us know.
