### ISSUE TITLE
Demo instance

### ISSUE THREAD

**Issue by drcandacemakedamoore** [bioinformatics-ua/dicoogle#467]
The demo instance (demo.dicoogle.com) is not working again. This was an issue back in 2019, and I added a comment to an old thread on it, but I am not sure anyone saw it.

**Comment by bastiao** [comment]
Hi @drcandacemakedamoore 
Thanks for reporting, we are awaare of it. The demo server had an issue, hopefully it can back soon. 
You can run the software offline, we do not consider it as an issue/bug with software, so I'm closing it.
