### ISSUE TITLE
While working with dicoogle server we are facing issues for memory

### ISSUE THREAD

**Issue by SuketuS** [bioinformatics-ua/dicoogle#485]
While running the dicoogle server on aks we have noticed that the memory is not coming down  probably garbage collection is not happening can some one help me on this. it stays at the same level even after it is not in use or 

![image](https://user-images.githubusercontent.com/9967158/125563418-a0ee5d40-57fb-4ee3-b9b8-dad5ebba0c47.png)

**Comment by Enet4** [comment]
Hello @SuketuS. Without more details (JVM version, settings applied, Dicoogle version, plugins used, etc.) it is not possible to understand what can be done to improve the experience here. Note that the JVM is responsible for defining how garbage is collected, and some implementations do not even return freed heap memory back to the operating system ([SO](https://stackoverflow.com/q/30458195/1233251)).

At first glance, this does not appear to be a problem with Dicoogle itself. If necessary, it is possible to tweak the JVM parameters such as the maximum heap size (`-Xmx`).

**Comment by SuketuS** [comment]
@Enet4 - We have tried multiple options for the JVM parameters including -Xmx and -XX:MaxMetaspaceSize also --Xmn options but still we are facing issues. where it is getting failed please find the options
java -Xms1650m -Xmx1650m -XX:MaxMetaspaceSize=200M -Xmn400m -Xss1M tried with 200 MB File Uncompreessed with parallel 2 users, however compressed file had better result, can you let me know if any thing we should be know about.

**Comment by Enet4** [comment]
> java -Xms1650m -Xmx1650m -XX:MaxMetaspaceSize=200M -Xmn400m -Xss1M

`-Xms1650m` would reserve this much heap memory on boot, and to the best of my knowledge, that would never be released to the OS.

Specifically what kind of issues were found when running Dicoogle with these parameters?

> can you let me know if any thing we should be know about.

Only that the memory requirements of Dicoogle are directly dependent on the kind of use made. The number and nature of plugins installed, number of images indexed over time, ... all of this can make Dicoogle perform poorly when it does not have enough memory. We generally do not deploy a Dicoogle archive with less than 2GB of dedicated heap memory, and in larger PACS, much more memory is reserved than this.

**Comment by Enet4** [comment]
Closing this issue, as this does not appear to outline a specific and actionable problem with the software. If necessary, you may obtain professional support by teaching out to BMD Software.
