### ISSUE TITLE
Add creation time to running task descriptor

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#510]
Tasks recorded in Dicoogle present the time elapsed when they are complete, but they do not keep track of the time when they were created or dispatched. This information would be useful to have, and would also allow applications to sort the list of running tasks consistently in chronological order. Without this, task entries at the web application may unexpectedly "hop" to different places or new ones may appear out of nowhere.

Acceptance criteria:

- The class type for tasks should be adjusted to record the date-time of creation, and the respective getter should be added
- At the web service for retrieving the list of running tasks, a new property for the creation time should appear in each result.
- At the web app, the Index menu should be tweaked to take advantage of this creation time, both by presenting it on each task element, and by sorting tasks in chronological descending order.

**Comment by RoboBaranik** [comment]
Hello, I would like to work on this issue.

**Comment by Enet4** [comment]
@RoboBaranik Great! Here is some guidance:

- `Task` is defined in the SDK. There should be no need to add anything else other than a private field and a public getter.
- [`RunningIndexTask`](https://github.com/bioinformatics-ua/dicoogle/blob/dev/dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java) contains the logic to serialize the tasks to JSON.

**Comment by sgaurav37533** [comment]
I can work on this issue please assign me this issue.

**Comment by RoboBaranik** [comment]
Sorry, but I already started working on this issue.

**Comment by Enet4** [comment]
@sgaurav37533 There are a few other [easy tasks](https://github.com/bioinformatics-ua/dicoogle/labels/good%20first%20issue) in the Dicoogle project for which we would gladly accept pull requests. E.g. #423, #341, #332

**Comment by RoboBaranik** [comment]
@Enet4 I have the implementation ready locally, but I am unable to push my feature branch to remote:
```
git push -u origin imp/creation-time-addition
remote: Permission to bioinformatics-ua/dicoogle.git denied to RoboBaranik.
fatal: unable to access 'https://github.com/bioinformatics-ua/dicoogle.git/': The requested URL returned error: 403
```

**Comment by Enet4** [comment]
> @Enet4 I have the implementation ready locally, but I am unable to push my feature branch to remote:
> 
> ```
> git push -u origin imp/creation-time-addition
> remote: Permission to bioinformatics-ua/dicoogle.git denied to RoboBaranik.
> fatal: unable to access 'https://github.com/bioinformatics-ua/dicoogle.git/': The requested URL returned error: 403
> ```

You can push it to your own fork, and then [create a pull request from your own fork](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by RoboBaranik** [comment]
Thank you for your response. Here is my pull request #511 .
