### ISSUE TITLE
LogDICOM in Dicoogle 3

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#528]
We have recent changes to stop emitting log lines to the old DICOMLOG file (#527) in Dicoogle 2. In Dicoogle 3, we need to think of a strategy which will avoid having related issues in the latest versions while fulfilling the necessary DICOM logging needs.

**Comment by Enet4** [comment]
@bastiao I propose that all DICOM log lines are replaced with slf4j log records for an upcoming version (patch or minor) of Dicoogle 3. Our logging framework isn't going away, and it is highly flexible in terms of what and how it outputs this information.

**Comment by bastiao** [comment]
Ok.
