### ISSUE TITLE
[webapp] Attribute content rows with misaligned width in image dump

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#56]
Whenever an attribute value is too large to fit in the table's fixed width, this happens:

![screenshot_2015-05-27_16-16-39](https://cloud.githubusercontent.com/assets/4738426/7914152/1cb28e50-086d-11e5-9783-b958e5aa7a61.png)

**Comment by fredericojssilva** [comment]
yes, I'm already aware.

**Comment by Enet4** [comment]
Closed via the merge of "bug/webapp/dump-style".
