### ISSUE TITLE
Dicoogle launches the old GUI client by default.

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#57]
Given that the GUI client is deprecated, we should also make sure that running the main executable without any arguments does not launch it by default. There are some alternatives:

- Start the server and open a web browser (if available) on the web application : `-w`
- Simply start the server : `-s`
- Terminate with an error and enforce the use of the current CLI arguments.

Which one should we choose?

**Comment by Enet4** [comment]
In a front-to-front conversation with @bastiao, it was clarified that Dicoogle should try to run the web application by default. I will address this in a moment.

**Comment by bastiao** [comment]
yes, clarified in face-to-face meeting. it will be merged.
