### ISSUE TITLE
Failed to execute goal on project dicoogle-sdk

### ISSUE THREAD

**Issue by lokutso** [bioinformatics-ua/dicoogle#576]
[INFO] ----------------------< pt.ua.ieeta:dicoogle-sdk >----------------------
[INFO] Building dicoogle-sdk 3.0.8-SNAPSHOT                               [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from mavencentral: https://repo1.maven.org/maven2/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom
Downloading from mi: https://bioinformatics.ua.pt/maven/content/repositories/mi/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom
Downloading from maven-restlet: https://maven.restlet.talend.com/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom
Downloading from dcm4che: https://www.dcm4che.org/maven2/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dicoogle-all 3.0.8-SNAPSHOT:
[INFO] 
[INFO] dicoogle-all ....................................... SUCCESS [  0.952 s]
[INFO] dicoogle-sdk ....................................... FAILURE [ 15.217 s]
[INFO] dicoogle ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.258 s
[INFO] Finished at: 2022-04-06T19:35:15+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dicoogle-sdk: Could not resolve dependencies for project pt.ua.ieeta:dicoogle-sdk:jar:3.0.8-SNAPSHOT: Failed to collect dependencies at fakepath:jspf.core:jar:1.0.2: Failed to read artifact descriptor for fakepath:jspf.core:jar:1.0.2: Could not transfer artifact fakepath:jspf.core:pom:1.0.2 from/to mi (https://bioinformatics.ua.pt/maven/content/repositories/mi): transfer failed for https://bioinformatics.ua.pt/maven/content/repositories/mi/fakepath/jspf.core/1.0.2/jspf.core-1.0.2.pom: Certificate for <bioinformatics.ua.pt> doesn't match any of the subject alternative names

**Comment by Enet4** [comment]
The error message given

> Certificate for <bioinformatics.ua.pt> doesn't match any of the subject alternative names

suggests that Maven could not validate the certificate of bioinformatics.ua.pt. Which version of the JDK are you using? Is it prepared to validate Let's Encrypt certificates?

**Comment by bastiao** [comment]
Please re-open this issue, if more information is provided.
