### ISSUE TITLE
cannot build the application with the given dockerfile

### ISSUE THREAD

**Issue by Prasannavenkatesh2598** [bioinformatics-ua/dicoogle#582]
[INFO] dicoogle-all ....................................... SUCCESS [01:11 min]
[INFO] dicoogle-sdk ....................................... FAILURE [01:59 min]
[INFO] dicoogle ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:11 min
[INFO] Finished at: 2022-05-30T07:40:27Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.4:check (default) on project dicoogle-sdk: Some files do not have the expected license header -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dicoogle-sdk
The command '/bin/sh -c ( cd dicoogle && mvn install && ln -s /root/dicoogle/dicoogle/target/dicoogle.jar /root/ )' returned a non-zero code: 1

**Comment by Enet4** [comment]
The given error suggests that there are changes in the code and that not all files have the license header. You can call `mvn license:format` on the project and try again. Can you please validate?
If there were no changes, then ensure that the latest revision is checked out (branches `dev` or `release/3.X`).

**Comment by Enet4** [comment]
The license headers are now checked in CI since #588. You probably stumbled upon the mistake in the `DIMGenericTest` class file, which is now fixed. Please comment if it is not the case.
