### ISSUE TITLE
Indexer batched unindexing

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#594]
The current definition for [`unindex`](https://github.com/bioinformatics-ua/dicoogle/blob/dev/sdk/src/main/java/pt/ua/dicoogle/sdk/IndexerInterface.java#L73) can take a single URI. As most implementations of this imply one index write for each removal, this constitutes a performance bottleneck.

If an overload was provided for unindexing a list of items, implementations could more easily attain better performance by writing all changes to the index in a batch, rather than flushing each operation one by one.

```java
public ? unindex(List<URI> path) throws ?;
```

**Comment by bastiao** [comment]
It is a nice idea coming from a real user story. :) Definitely, we should go for it.
