### ISSUE TITLE
npm run build hands-on

### ISSUE THREAD

**Issue by FUTURE724** [bioinformatics-ua/dicoogle#610]
I am currently at the stage where I am trying to run the following code:

`npm run build `

I am getting the error below:
npm ERR! Missing script: "build"

These are the scripts in the package.json file:
` "scripts": {
    "build": "webpack --config webpack.prod.js",
    "start": "webpack-dev-server --open --config webpack.dev.js",
    "precommit": "lint-staged",
    "build-debug": "webpack --config webpack.dev.js --progress",
    "clean": "rimraf dist/* index.html",
    "webpack": "webpack --config webpack.prod.js --progress",
    "postinstall": "cd ../../../../../webcore && npm install --production --no-fund"
  },`

**Comment by Enet4** [comment]
npm is only used for building the webapp manually. You can use Maven to build everything in one step using `mvn install` or `mvn package`. To build the webapp separately, please ensure that your working directory is `«repo_root»/dicoogle/src/main/resources/webapp` and run `npm install` there.

See also the learning pack for more details on [building Dicoogle](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/building/).
