### ISSUE TITLE
cannot push image

### ISSUE THREAD

**Issue by beavermml** [bioinformatics-ua/dicoogle#627]
error is : cannot negotiate network association: No acceptable Presentation Contexts

**Comment by beavermml** [comment]
![image](https://user-images.githubusercontent.com/3795219/203220951-88fea6c3-e81c-4286-9689-42c040263b7a.png)
Tranfer Syntax : 1.2.840.10008.1.2.1 (Explicit VR Little Endian)
SOP Class : 1.2.840.10008.5.1.4.1.1.2

**Comment by beavermml** [comment]
what i have done

1. open DCM in MicroDicom DICOM Viewer
2. send the image to PACS server 
3. fail

1. copy DCM to the server storage folder ( watch enable )
2. see the log that Dicoogle processing the files
3 . Dicoogle didnt index the file

**Comment by Enet4** [comment]
> 1. open DCM in MicroDicom DICOM Viewer
> 2. send the image to PACS server
> 3. fail

Could you clarify which errors emerge? What does the server configuration file (confs/server.xml) say about the storage transfer options for SOP Class `1.2.840.10008.5.1.4.1.1.2`?

> 4. copy DCM to the server storage folder ( watch enable )
> 5. see the log that Dicoogle processing the files
>    3 . Dicoogle didnt index the file

If you can share the logs of this sequence, it may be helpful. It is also possible to invoke file indexing manually without the directory watcher, by entering the webapp and inserting the URI in the  Indexer page. https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/using/#indexing-a-directory

**Comment by beavermml** [comment]
upgrade to 3.2.0 but still has the same problem too

**Comment by Enet4** [comment]
> > What does the server configuration file (confs/server.xml) say about the storage transfer options for SOP Class 1.2.840.10008.5.1.4.1.1.2?
> 
> ![image](https://user-images.githubusercontent.com/3795219/204692971-f58cafd1-25cc-42a7-b670-45d07495e200.png)

In the same file, are the intended transfer syntaxes listed in element `<default-ts>`? One may have to define the accepted transfer syntaxes manually.

The screenshots suggest that no DICOM files were not found in the directory given.

**Comment by beavermml** [comment]
![image](https://user-images.githubusercontent.com/3795219/210459999-4d277df4-66c3-463c-a0fa-dbbe7856ddbb.png)

**Comment by Enet4** [comment]
This is peculiar. It would really help if you could provide a fully anonymized version of the DICOM file. It does not even need to have pixel data or any other PHI. Leaving the transfer syntax and SOP class UIDs intact might be enough for us to reproduce the problem.

**Comment by beavermml** [comment]
[anon.zip](https://github.com/bioinformatics-ua/dicoogle/files/10422992/anon.zip)

sorry for late reply.. this is the file
