### ISSUE TITLE
How to realize image film printing

### ISSUE THREAD

**Issue by learnr27** [bioinformatics-ua/dicoogle#628]
Can you provide a demo

**Comment by learnr27** [comment]
DICOM Print

**Comment by Enet4** [comment]
If you can write an intermediary script to retrieve the intended files from the archive, it may also create a printing session with the DICOM printer. The built-in Dicoogle system does not provide direct support for DICOM printers, and it is not in the project's plans to implement this. If hiring a consulting service is an option, consider reaching out to [BMD Software](https://www.bmd-software.com).
