### ISSUE TITLE
How to download dcm file from dicoogle pacs?

### ISSUE THREAD

**Issue by linthu33** [bioinformatics-ua/dicoogle#648]

**Comment by Enet4** [comment]
Dicoogle provides a standard DICOM query/retrieval service which allows you to fetch the DICOM files via C-STORE. You can do this using a move SCU such as the one from [Dcmtk](https://support.dcmtk.org/docs/movescu.html).

```
movescu --study --port 9876 -aec DICOOGLE-STORAGE dicoogle.example.com 1045 q.dcm
```

Downloading files from the archive's web interface is not available as a built-in feature (although plugins could provide it).
