### ISSUE TITLE
Error running Sample Plugin

### ISSUE THREAD

**Issue by mwongeraE** [bioinformatics-ua/dicoogle#656]
Hello,

I have been trying to run the sample plugin provided here: https://github.com/bioinformatics-ua/dicoogle-plugin-sample

The plugin fails to build with this error:
`[ERROR] Failed to execute goal on project dicoogle-plugin-sample: Could not resolve dependencies for project pt.ua.dicoogle.demo:dicoogle-plugin-sample:jar:3.0.0: Failed to collect dependencies at pt.ua.ieeta:dicoogle-sdk:jar:3.2.0:`

Has anyone else encountered this?
Thanks.

**Comment by Enet4** [comment]
Thank you for reporting. Let us track this issue at the plugin sample repository: https://github.com/bioinformatics-ua/dicoogle-plugin-sample/pull/15

**Comment by mwongeraE** [comment]
Thank for updating the plugin. @Enet4
