### ISSUE TITLE
Error resolving dependencies

### ISSUE THREAD

**Issue by concernedrat** [bioinformatics-ua/dicoogle#688]
Tried to build the project from scratch. Accessing the repository [https://dev.bmd-software.com/nexus/content/repositories/dicoogle-public](https://dev.bmd-software.com/nexus/content/repositories/dicoogle-public) gives an internal server error (500) .

**Comment by Enet4** [comment]
There does not appear to be any issue with the repository right now. Can you give it another try?

**Comment by concernedrat** [comment]
It is solved now :) thank you for the follow up.
