### ISSUE TITLE
Using the mvn install the filestorage.jar error

### ISSUE THREAD

**Issue by Jessica217** [bioinformatics-ua/dicoogle#689]
I tried open the "http://bioinformatics.ua.pt/maven/content/repositories/mi/pt/ua/ieeta/dicoogle-sdk/3.0.0/dicoogle-sdk-3.0.0.pom" but failed, the website showed the "503 Seivice Uavailable"
It seems like this issue: https://github.com/bioinformatics-ua/dicoogle/issues/392

**Comment by bastiao** [comment]
Dicoogle SDK can be built from source.

**Comment by Enet4** [comment]
The repository for Dicoogle artifacts was recently relocated to https://dev.bmd-software.com/nexus/content/repositories/dicoogle-public. Existing plugin maven projects need to be updated accordingly.

You would find the SDK in https://dev.bmd-software.com/nexus/content/repositories/dicoogle-public/pt/ua/ieeta/dicoogle-sdk/3.3.6/dicoogle-sdk-3.3.6.pom.

**Comment by Enet4** [comment]
Closing as this does not constitute a problem with the core software, and existing documentation and sample projects have already been updated to the current Maven repository.
