### ISSUE TITLE
How to set up a WADO-RS service

### ISSUE THREAD

**Issue by yansen-zh** [bioinformatics-ua/dicoogle#697]
I need to set up a WADO-RS service, and this service needs to connect to another AE, which is not managed by me. Is there any way to achieve this?

**Comment by Enet4** [comment]
WADO-RS support is currently only available as extensions to Dicoogle. Please reach out to [BMD Software](https://www.bmd-software.com) if you are interested.

See also: https://github.com/bioinformatics-ua/dicoogle/issues/454
