### ISSUE TITLE
Handle CORS properly

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#74]
Many of our servlets are currently accepting all origins, which is not safe. This should be carefully reconsidered, and we may start by removing all "Access-Control-Allow-Origin" header assignments in the servlets.

**Comment by bastiao** [comment]
@Enet4 you're right. It was only added for debug checking. The solution will be: only add it, if we are in DEBUG mode. But it will be nice to have it only in one place in Jetty. do you know if it possible?

**Comment by Enet4** [comment]
Yes, we can add a [Cross Origin filter](http://www.eclipse.org/jetty/documentation/current/cross-origin-filter.html) in `DicoogleWeb`.

**Comment by bastiao** [comment]
sounds good.

**Comment by Enet4** [comment]
An update: I've been tinkering with `CrossOriginFilter` for quite a while, but it still fails to have any effect on the responses. Since we know how to add these headers anyway, I will try next to make my own filter.
