### ISSUE TITLE
Licenses: put the license of the software that we're using

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#82]
A directory in the root maybe created with:
- licenses/server/
- licenses/client/

Then it could be like: react.js.txt and the license inside.

**Comment by Enet4** [comment]
Just updating with a notice that some of the licenses in the "About" page are wrong. React is licensed with BSD, not GPL.

**Comment by bastiao** [comment]
You're right. They changed from Apache Licence clauses to BSD in 0.12 or 0.13.  In case of updating version of libraries, we should keep also update the license (and yes, it was wrong anyway).
